# Generated by Django 4.2.5 on 2023-10-10 06:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=120)),
                ('contact', models.CharField(default='', max_length=15)),
                ('image', models.ImageField(upload_to='field/')),
                ('price_per_hour', models.IntegerField(default=50)),
                ('stadium_length', models.IntegerField(default=10)),
                ('stadium_width', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='ReserveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('start_time', models.CharField(default='', max_length=50)),
                ('end_time', models.CharField(default='', max_length=50)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.fieldmodel')),
            ],
        ),
    ]
