# Generated by Django 4.2.5 on 2023-10-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_fieldmodel_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservemodel',
            table='book',
        ),
    ]
